config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'books/results_index' => 'books#results_index'
  post 'books/result' => 'books#url_from_keyword'
  root to: 'books#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
require 'net/http'
require 'uri'
require 'json'
require 'httparty'

class BooksController < ApplicationController
    include BooksApi

    def results_index
        @results = @@results
    end

    def search
    end

    def url_from_keyword
        keyword = params[:keyword]
        results = BooksApi.get_url(keyword)
        @@results = results.parsed_response
        redirect_to(books_results_index_path)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/results_index.html.erb
<% for i in 0..14 do %>
        <div>
            <% if @results["items"][i]["volumeInfo"]["title"].nil? %>
                <p>情報がありません</p>
            <% else %>
                <p>タイトル：<%= @results["items"][i]["volumeInfo"]["title"] %></p>
            <% end %>
            <% if @results["items"][i]["volumeInfo"]["authors"].nil? %>
                <p>情報がありません</p>
            <% else %>
                <p>著者：<%= @results["items"][i]["volumeInfo"]["authors"][0] %></p>
            <% end %>
            <% if @results["items"][i]["volumeInfo"]["imageLinks"].nil? %>
                <p>情報がありません</p>
            <% else %>
                <img src="<%= @results["items"][i]["volumeInfo"]["imageLinks"]["thumbnail"] %>" >
            <% end %>
        </div>
<% end %>

app/views/books/search.html.erb
<div class="content">
    <div id="search-box">
        <%= form_tag(books_result_path, method: :post) do %>
            <input type="text" name="keyword" id="keyword">
            <button type="submit">検索</button>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppName</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>